config/routes.rb
SeatShare::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => {:registrations => "registrations"}, :path => '/', :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }

  # Default route for app is authenticated, so will redirect
  root 'groups#current'

  devise_scope :user do
    get "register/group/:group_code", to: "registrations#new", as: 'register_with_group_code'
    get "register/invite/:invite_code", to: "registrations#new", as: 'register_with_invite_code'
    get "register/:entity_slug/:entity_id", to: "registrations#new", as: 'register_with_entity_id'
  end

  get 'groups/' => 'groups#index'
  get 'groups/new' => 'groups#new', as: 'new_group'
  post 'groups/new' => 'groups#create'
  get 'groups/join' => 'groups#join', as: 'join_group'
  post 'groups/join' => 'groups#do_join'
  get 'groups/join/:invite_code' => 'groups#join'
  get 'groups/:id' => 'groups#show', as: 'group'
  get 'groups/:id/edit' => 'groups#edit', as: 'edit_group'
  patch 'groups/:id/edit' => 'groups#update'
  post 'groups/:id/notifications/edit' => 'groups#update_notifications'
  get 'groups/:id/leave' => 'groups#leave', as: 'leave_group'
  patch 'groups/:id/leave' => 'groups#do_leave'
  get 'groups/:id/invite' => 'groups#invite', as: 'invite_group'
  post 'groups/:id/invite' => 'groups#do_invite'
  post 'groups/:id/reset_invite' => 'groups#do_reset_invite'
  get 'groups/:id/deactivate' => 'groups#deactivate', as: 'deactivate_group'
  patch 'groups/:id/deactivate' => 'groups#do_deactivate'
  get 'groups/:id/message' => 'groups#message', as: 'message_group'
  post 'groups/:id/message' => 'groups#do_message'
  get 'groups/:id/events_feed' => 'groups#events_feed'
  post 'groups/:id/schedule_notify' => 'groups#do_request_notify'

  get 'groups/:group_id/event-:id' => 'events#show'

  get 'groups/:group_id/event-:event_id/ticket-:id' => 'tickets#edit'
  post 'groups/:group_id/event-:event_id/ticket-:id' => 'tickets#update'
  get 'groups/:group_id/event-:event_id/ticket-:id/unassign' => 'tickets#unassign'
  get 'groups/:group_id/event-:event_id/ticket-:id/delete' => 'tickets#delete'
  get 'groups/:group_id/event-:event_id/ticket-:ticket_id/ticket-file/:id/delete' => 'tickets#delete_ticket_file', as: 'delete_ticket_file'
  get 'groups/:group_id/add-tickets' => 'tickets#new'
  post 'groups/:group_id/add-tickets' => 'tickets#create'
  get 'groups/:group_id/event-:event_id/add-ticket' => 'tickets#new'
  post 'groups/:group_id/event-:event_id/add-ticket' => 'tickets#create'
  get 'groups/:group_id/event-:event_id/ticket-:id/request' => 'tickets#request_ticket'
  patch 'groups/:group_id/event-:event_id/ticket-:id/request' => 'tickets#do_request_ticket'

  get 'tickets' => 'tickets#index'
  get 'tickets/:filter' => 'tickets#index'
  post 'tickets' => 'tickets#bulk_update'

  get 'calendar' => 'calendar#index'
  get 'calendar/full/:token' => 'calendar#full'
  get 'groups/:group_id/calendar/:token' => 'calendar#group'

  resource :user, path: 'profile', only: [:show, :edit, :update] do
    resources :aliases, controller: :user_aliases
  end
  resources :users, path: 'profiles', only: [:show]

  match '/404' => 'errors#error404', via: [:get, :post, :patch, :delete]

  namespace :admin_api, defaults: {format: 'json'} do
    namespace :v1 do
      root 'admin_api#index'
      get ':action' => 'admin_api#:action'
    end
  end

end

app/controllers/user_aliases_controller.rb
##
# User Aliases class
class UserAliasesController < ApplicationController
  before_action :authenticate_user!
  layout 'two-column'

  ##
  # New user alias form
  def new
    @user_alias = UserAlias.new
  end

  ##
  # Process new user alias
  def create
    user_alias = UserAlias.new(
      first_name: user_alias_params[:first_name],
      last_name: user_alias_params[:last_name],
      user_id: current_user.id
    )
    flash.keep
    if user_alias.save
      flash[:notice] = 'User alias created!'
      redirect_to(controller: :users, action: :edit) && return
    else
      flash[:error] = 'Could not create User Alias.'
      redirect_to(controller: :user_aliases, action: :new) && return
    end
  end

  ##
  # Edit user alias form
  def edit
    @user_alias = UserAlias.find_by(id: params[:id]) || not_found
    redirect_to(controller: :users, action: :edit) \
      if @user_alias.user_id != current_user.id
  end

  ##
  # Process user alias updates
  def update
    user_alias = UserAlias.find_by(id: params[:id]) || not_found
    user_alias.first_name = user_alias_params[:first_name]
    user_alias.last_name = user_alias_params[:last_name]
    flash.keep
    if user_alias.save
      flash[:notice] = 'User Alias updated!'
      redirect_to(controller: :users, action: :edit) && return
    else
      flash[:error] = 'Could not update User Alias.'
      redirect_to(
        controller: :user_aliases, action: :edit, id: user_alias.id
      ) && return
    end
  end

  ##
  # Process a user alias delete
  def destroy
    user_alias = UserAlias.find_by(id: params[:id]) || not_found
    if user_alias.user_id != current_user.id
      redirect_to(controller: :users, action: :edit) && return
    end
    user_alias.destroy
    flash.keep
    flash[:notice] = 'User Alias deleted.'
    redirect_to(controller: :users, action: :edit) && return
  end

  private

  ##
  # Strong parameters for user aliases
  def user_alias_params
    params.require(:user_alias).permit(:first_name, :last_name, :user_id)
  end
end

app/helpers/user_aliases_helper.rb
##
# User Aliases helper
module UserAliasesHelper
end

app/views/user_aliases/edit.html.erb
<% content_for :page_title do %>Edit User Alias<% end %>

<%= form_for @user_alias, url: user_alias_path, html: {class: "form-horizontal", role: "form"} do |f| %>

  <fieldset>
    <legend>User Alias details</legend>

    <div class="form-group">
      <%= f.label :first_name, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :first_name, :class => 'form-control', :placeholder => 'John', :value => @user_alias.first_name %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :last_name, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :last_name, :class => 'form-control', :placeholder => 'Doe', :value => @user_alias.last_name %>
      </div>
    </div>

  </fieldset>

  <div class="row">
    <div class="col-md-12">
        <p class="text-right">
          <%= f.submit 'Update User Alias', :class => 'btn btn-primary' %>
        </p>
    </div>
  </div>

<% end %>

<% content_for :page_footer do %>
<% end %>

app/views/user_aliases/new.html.erb
<% content_for :page_title do %>Add User Alias<% end %>

<%= form_for @user_alias, url: user_aliases_path, html: {class: "form-horizontal", role: "form"} do |f| %>

  <fieldset>
    <legend>User Alias details</legend>

    <div class="form-group">
      <%= f.label :first_name, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :first_name, :class => 'form-control', :placeholder => 'John' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :last_name, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :last_name, :class => 'form-control', :placeholder => 'Doe' %>
      </div>
    </div>

  </fieldset>

  <div class="row">
    <div class="col-md-12">
        <p class="text-right">
          <%= f.submit 'Create User Alias', :class => 'btn btn-primary' %>
        </p>
    </div>
  </div>

<% end %>

<% content_for :page_footer do %>
<% end %>