config/routes.rb
SeatShare::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => {:registrations => "registrations"}, :path => '/', :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }

  # Default route for app is authenticated, so will redirect
  root 'groups#current'

  devise_scope :user do
    get "register/group/:group_code", to: "registrations#new", as: 'register_with_group_code'
    get "register/invite/:invite_code", to: "registrations#new", as: 'register_with_invite_code'
    get "register/:entity_slug/:entity_id", to: "registrations#new", as: 'register_with_entity_id'
  end

  get 'groups/' => 'groups#index'
  get 'groups/new' => 'groups#new', as: 'new_group'
  post 'groups/new' => 'groups#create'
  get 'groups/join' => 'groups#join', as: 'join_group'
  post 'groups/join' => 'groups#do_join'
  get 'groups/join/:invite_code' => 'groups#join'
  get 'groups/:id' => 'groups#show', as: 'group'
  get 'groups/:id/edit' => 'groups#edit', as: 'edit_group'
  patch 'groups/:id/edit' => 'groups#update'
  post 'groups/:id/notifications/edit' => 'groups#update_notifications'
  get 'groups/:id/leave' => 'groups#leave', as: 'leave_group'
  patch 'groups/:id/leave' => 'groups#do_leave'
  get 'groups/:id/invite' => 'groups#invite', as: 'invite_group'
  post 'groups/:id/invite' => 'groups#do_invite'
  post 'groups/:id/reset_invite' => 'groups#do_reset_invite'
  get 'groups/:id/deactivate' => 'groups#deactivate', as: 'deactivate_group'
  patch 'groups/:id/deactivate' => 'groups#do_deactivate'
  get 'groups/:id/message' => 'groups#message', as: 'message_group'
  post 'groups/:id/message' => 'groups#do_message'
  get 'groups/:id/events_feed' => 'groups#events_feed'
  post 'groups/:id/schedule_notify' => 'groups#do_request_notify'

  get 'groups/:group_id/event-:id' => 'events#show'

  get 'groups/:group_id/event-:event_id/ticket-:id' => 'tickets#edit'
  post 'groups/:group_id/event-:event_id/ticket-:id' => 'tickets#update'
  get 'groups/:group_id/event-:event_id/ticket-:id/unassign' => 'tickets#unassign'
  get 'groups/:group_id/event-:event_id/ticket-:id/delete' => 'tickets#delete'
  get 'groups/:group_id/event-:event_id/ticket-:ticket_id/ticket-file/:id/delete' => 'tickets#delete_ticket_file', as: 'delete_ticket_file'
  get 'groups/:group_id/add-tickets' => 'tickets#new'
  post 'groups/:group_id/add-tickets' => 'tickets#create'
  get 'groups/:group_id/event-:event_id/add-ticket' => 'tickets#new'
  post 'groups/:group_id/event-:event_id/add-ticket' => 'tickets#create'
  get 'groups/:group_id/event-:event_id/ticket-:id/request' => 'tickets#request_ticket'
  patch 'groups/:group_id/event-:event_id/ticket-:id/request' => 'tickets#do_request_ticket'

  get 'tickets' => 'tickets#index'
  get 'tickets/:filter' => 'tickets#index'
  post 'tickets' => 'tickets#bulk_update'

  get 'calendar' => 'calendar#index'
  get 'calendar/full/:token' => 'calendar#full'
  get 'groups/:group_id/calendar/:token' => 'calendar#group'

  resource :user, path: 'profile', only: [:show, :edit, :update] do
    resources :aliases, controller: :user_aliases
  end
  resources :users, path: 'profiles', only: [:show]

  match '/404' => 'errors#error404', via: [:get, :post, :patch, :delete]

  namespace :admin_api, defaults: {format: 'json'} do
    namespace :v1 do
      root 'admin_api#index'
      get ':action' => 'admin_api#:action'
    end
  end

end

app/controllers/groups_controller.rb
##
# Groups controller
class GroupsController < ApplicationController
  before_action :authenticate_user!
  layout 'two-column', except: [:index]

  ##
  # Index view of groups or welcome page
  def index
    @groups = current_user.groups.active
    render 'groups/welcome' if @groups.blank?
  end

  ##
  # Go to last active group
  def current
    if session[:current_group_id].is_a? Numeric
      redirect_to(
        controller: 'groups', action: 'show',
        id: session[:current_group_id], status: 302
      ) && return
    else
      redirect_to(
        controller: 'groups', action: 'index'
      )
    end
  end

  ##
  # New group form
  def new
    active_entities = Entity.active.includes(:entity_type).order(
      'entity_types.sort ASC'
    ).by_name
    @entity = Entity.find_by(id: params[:entity_id])
    options = {}
    active_entities.each_with_object({}) do |e|
      (options[e.entity_type.display_name] ||= []) << [e.entity_name, e.id]
    end
    @entities = options
    @group = Group.new
  end

  ##
  # Processes a new group
  def create
    entity = Entity.find_by(id: group_params[:entity_id]) || not_found
    group = Group.new(
      group_name: "#{entity.entity_name} Group",
      entity_id: group_params[:entity_id],
      creator_id: current_user.id
    )
    if group.save
      group.entity.seatgeek_import if group.events.future.empty?
      group.join_group current_user, 'admin'
      flash.keep
      flash[:notice] = 'Group created!'
      redirect_to action: 'show', id: group.id
    else
      flash.keep
      flash[:error] = 'Group could not be created.'
      redirect_to action: 'new', entity_id: params[:entity_id]
    end
  end

  ##
  # Edit group form
  def edit
    @group = Group.find_by(id: params[:id]) || not_found
    redirect_to(action: 'index') && return unless @group.member?(current_user)
    @members = @group.members.by_name
    @membership = Membership.where(
      "user_id = #{current_user.id} AND group_id = #{@group.id}"
    ).first
  end

  ##
  # Process group edits
  def update
    group = Group.find(params[:id]) || not_found
    raise 'NotGroupAdmin' unless group.admin?(current_user)
    group.group_name = group_params[:group_name]
    group.avatar = group_params[:avatar] unless group_params[:avatar].nil?
    group.avatar = nil if group_params[:remove_avatar] == '1'
    if group.save
      flash[:notice] = 'Group updated!'
    else
      flash[:error] = 'Group could not be updated.'
    end
    redirect_to(
      controller: 'groups', action: 'show', id: group.id
    ) && return
  end

  ##
  # Process notification edits
  def update_notifications
    group = Group.find(params[:id]) || not_found
    raise 'NotGroupMember' unless group.member?(current_user)
    daily = params[:membership][:daily_reminder]
    weekly = params[:membership][:weekly_reminder]
    mine = params[:membership][:mine_only]
    flash.keep
    status = Membership
             .where(user_id: current_user.id, group_id: group.id)
             .each do |membership|
               membership.update_attributes(
                 daily_reminder: daily, weekly_reminder: weekly, mine_only: mine
               )
             end
    if status
      flash[:notice] = 'Reminder settings updated!'
    else
      flash[:error] = 'Reminder settings could not be updated.'
      redirect_to(
        controller: 'groups', action: 'edit', id: group.id
      ) && return
    end
    redirect_to(
      controller: 'groups', action: 'show', id: group.id
    ) && return
  end

  ##
  # Initial page after login for a group member
  def show
    @group = Group.find_by(id: params[:id]) || not_found
    @entity = @group.entity
    not_found unless @group.status?
    redirect_to(action: 'index') && return unless @group.member?(current_user)
    @events = @group.events.future.confirmed.by_date
    @members = @group.members.by_name
    session[:current_group_id] = @group.id
  end

  ##
  # JSON feed for calendar widget
  def events_feed
    @group = Group.find_by(id: params[:id]) || not_found
    not_found unless @group.status?
    raise 'NotGroupMember' unless @group.member?(current_user)
    @events = @group.events.confirmed.by_date

    feed = []
    @events.each do |event|
      next if event.date_tba == true
      event_link = url_for(
        controller: 'events', action: 'show', group_id: @group.id,
        id: event.id
      )
      feed << {
        date: event.start_time.strftime('%Y-%m-%d'),
        title: "#{event.time != '' ? event.time : 'TBA'} - #{event.event_name}",
        url: event_link,
        ticket_stats: event.ticket_stats(@group, current_user)
      }
    end
    render json: feed
  end

  ##
  # Join a group form
  def join
    @invite_code = params[:invite_code]
  end

  ##
  # Process a group join
  def do_join
    flash.keep
    begin
      # Use group invitation
      group = Group.find_by(invitation_code: params[:group][:invitation_code])
      # Fall back to normal user invitation
      if group.blank?
        invitation = GroupInvitation.get_by_invitation_code(
          params[:group][:invitation_code]
        )
        invitation.use_invitation
        group = invitation.group
      end
      group.join_group(current_user, 'member')
      flash[:notice] = 'Group joined!'
      redirect_to(action: 'show', id: group.id) && return
    rescue
      flash[:error] = 'The provided invitation code has already been used.'
      redirect_to(action: 'join') && return
    end
  end

  ##
  # Leave a group form
  def leave
    @group = Group.find_by(id: params[:id]) || not_found
    redirect_to(action: 'show', id: @group.id) && return \
      if @group.admin?(current_user)
  end

  ##
  # Process leaving a group
  def do_leave
    flash.keep
    user = if params[:user_id]
             User.find(params[:user_id])
           else
             current_user
           end
    group = Group.find_by(id: params[:id]) || not_found
    if user != current_user && !group.admin?(current_user)
      flash[:error] = 'You do not have permission to remove other users.'
      redirect_to(action: 'show', id: group.id) && return
    end
    group.leave_group(user)
    flash[:notice] = if user == current_user
                       "You have left #{group.group_name}"
                     else
                       "#{user.display_name} has been removed"
                     end
    if group.admin?(current_user)
      redirect_to(action: 'edit', id: group.id) && return
    else
      redirect_to(controller: 'groups', action: 'index') && return
    end
  end

  ##
  # Deactivate Group
  def deactivate
    @group = Group.find_by(id: params[:id]) || not_found
    redirect_to(action: 'show', id: @group.id) && return \
      unless @group.admin?(current_user)
  end

  ##
  # Process a group deactivation
  def do_deactivate
    group = Group.find(params[:id]) || not_found
    if group.deactivate
      flash[:notice] = 'Your group has been deactivated!'
      session.delete :current_group_id
    else
      flash[:error] = 'Unable to deactivate your group.'
    end
    redirect_to(
      action: 'index'
    ) && return
  end

  ##
  # Invite to a group form
  def invite
    @group = Group.find(params[:id]) || not_found
    @group_invitation = GroupInvitation.new
    @invite_link = "#{request.protocol}#{request.host_with_port}"\
      "#{new_user_registration_path}/group/#{@group.invitation_code}"
  end

  ##
  # Process a group invitation
  def do_invite
    group = Group.find(params[:id]) || not_found
    group_invitation = GroupInvitation.new(
      group_id: group.id,
      user_id: current_user.id,
      email: params[:group_invitation][:email]
    )
    flash.keep
    if group_invitation.save!
      GroupNotifier.create_invite(
        group_invitation,
        params[:group_invitation][:message]
      ).deliver_now
      flash[:notice] = 'Group invitation sent!'
    else
      flash[:error] = 'Unable to send group invitation.'
    end
    redirect_to(action: 'show', id: group.id) && return
  end

  ##
  # Process a group invitaiton code reset
  def do_reset_invite
    group = Group.find(params[:id]) || not_found
    raise 'AccessDenied' unless group.admin?(current_user)
    group.invitation_code = nil
    group.save!
    flash.keep
    flash[:notice] = 'Invitation code reset!'
    redirect_to(action: 'edit', id: group.id) && return
  end

  ##
  # Group message form
  def message
    @group = Group.find(params[:id]) || not_found
    @members = @group.members.by_name
  end

  ##
  # Process sending a group message
  def do_message
    group = Group.find(params[:id]) || not_found
    flash.keep
    if params[:message][:recipients].blank?
      flash[:error] = 'You must select at least one recipient.'
      redirect_to(action: 'message', id: group.id) && return
    end
    subject = params[:message][:subject]
    message = params[:message][:message]
    recipients = User.find(params[:message][:recipients])
    email = GroupNotifier.send_group_message(
      group, current_user, recipients, subject, message
    ).deliver_now
    flash.keep
    if email
      flash[:notice] = 'Message sent!'
      redirect_to(action: 'show', id: group.id) && return
    else
      flash[:error] = 'Message delivery failed.'
      redirect_to(action: 'message', id: group.id) && return
    end
  end

  def do_request_notify
    group = Group.find(params[:id]) || not_found
    ContactMailer.support_ticket(
      current_user.display_name,
      current_user.email,
      "Requesting #{group.entity.entity_name} schedule",
      "Requestor: #{current_user.display_name}\n"\
        "Group Name: #{group.display_name}\n"\
        "Entity: #{group.entity.entity_name}"
    ).deliver_now
    flash[:notice] = 'Schedule request sent!'
    redirect_to(action: 'show', id: group.id) && return
  end

  private

  ##
  # Strong parameters for groups
  def group_params
    params.require(:group).permit(

app/helpers/groups_helper.rb
##
# Groups helper
module GroupsHelper
end

app/views/groups/deactivate.html.erb
<% content_for :page_title do %><%= "Deactivate #{@group.group_name}" %><% end %>

<%= form_for @group, html: {class: "form-horizontal", role: "form"}, url: { :controller => 'groups', :action => 'deactivate', :id => @group.id } do |f| %>

<div class="alert alert-danger alert-block">
	<h3>Are you sure you want to deactivate "<strong><%= @group.group_name %></strong>?"</h3>
	<ul class="list">
		<li>All members will lose access to the group.</li>
		<li>All members will lose access to their past and future tickets.</li>
		<li>No further schedule reminders will be sent.</li>
	</ul>
	<p class="text-right">
		<%= f.hidden_field :id, :value => @group.id %>
		<%= f.submit 'Deactivate the Group', :class => 'btn btn-danger' %>
	</p>
</div>

<% end %>

<% content_for :page_footer do %>
<% end %>

app/views/groups/edit.html.erb
<% content_for :page_title do %>Edit Group<% end %>

<% if @group.admin?(current_user) %>

<%= form_for @group, url: edit_group_path, html: { class: "form-horizontal", role: "form", multipart: true } do |f| %>

<fieldset>
  <legend>Group Details</legend>

  <div class="form-group">
    <%= f.label :group_name, 'Group Name', :class => 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_field :group_name, :class => 'form-control', :placeholder => 'Cellblock 303', :value => @group.group_name %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :invitation_code, 'Share Link', class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <p class="form-control-static">
        <span class="text-muted"><%= "#{request.protocol}#{request.host_with_port}#{new_user_registration_path}" %>/group/</span><%= @group.invitation_code %>
        <ul class="list-inline">
          <li class="hidden-sm hidden-xs"><span class="btn btn-primary btn-xs btn-clipboard" data-clipboard-text="<%= "#{request.protocol}#{request.host_with_port}#{new_user_registration_path}" %>/group/<%= @group.invitation_code %>"><i class="fa fa-clipboard"></i> Copy to Clipboard</span></li>
          <li><%= link_to raw('<i class="fa fa-recycle"></i> Reset invitation code'), { :controller => 'groups', :action => 'do_reset_invite', :id => @group.id }, :class => 'btn btn-xs btn-danger', :method => 'post' %></li>
        </ul>
      </p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :avatar, :class => 'col-md-3 control-label' %>
    <div class="col-md-9">
      <% if !@group.avatar.nil? %>
      <%= image_tag @group.avatar.url(:thumb), :class => "img-thumbnail" %><br />
      <label><%= check_box_tag 'group[remove_avatar]', 1 %> Remove?</label>
      <br />
      <% end %>
      <%= f.file_field :avatar %>
    </div>
  </div>

</fieldset>

<div class="row">
  <div class="text-right col-md-12">
    <%= f.hidden_field :form_type, :value => 'group' %>
    <%= link_to 'Deactivate Group', deactivate_group_path, :class => 'btn btn-danger' %>
    <%= f.submit 'Update Group', :class => 'btn btn-primary' %>
  </div>
</div>

<% end %>

<% else %>

<fieldset>
  <legend>Group Details</legend>

  <p class="lead">You are a member of <strong><%= @group.group_name %></strong>, a <strong><%= @group.entity.entity_name %></strong> group. You can choose to receive reminders when there is an upcoming event for this group.</p>

</fieldset>

<div class="row">
  <div class="text-right col-md-12">
    <%= link_to raw('<span class="fa fa-eject"></span> Leave Group'), { :action => 'leave', :id => @group.id }, :class => 'btn btn-large btn-danger' %>
  </div>

</div>

<% end %>

<fieldset>
  <legend>Group Members</legend>
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th class="action"></th>
          <th>Name</th>
          <th>Email</th>
          <% if @group.admin?(current_user) %>
            <th class="action"></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% for member in @members %>
        <tr>
          <td><%= image_tag member.gravatar, :alt => member.display_name, :title => member.display_name %></td>
          <td><%= link_to member.display_name, {:controller => :users, :action => :show, :id => member.id } %></td>
          <td><%= mail_to member.email %></td>
          <% if @group.admin?(current_user) %>
            <td class="remove-user">
              <% if member != current_user %>
                <%= link_to raw('<span class="fa fa-trash"></span>'), { :action => 'leave', :user_id => member.id, :id => @group.id }, :class => 'btn btn-sm btn-danger confirm', :method => 'patch' %>
              <% else %>
                <div data-toggle="tooltip" title="You cannot leave this group."><span class="btn btn-sm btn-danger disabled"><i class="fa fa-trash"></i></span></div>
              <% end %>
            </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="text-right">
    <ul class="list-inline">
      <li><%= link_to raw('<span class="fa fa-envelope"></span> Message'), { :controller => 'groups', :action => 'message', :id => @group.id }, :class => 'btn btn-default' %></li>
      <li><%= link_to raw('<span class="fa fa-plus"></span> Invite'), { :controller => 'groups', :action => 'invite', :id => @group.id }, :class => 'btn btn-default' %></li>
    </ul>
  </div>

</fieldset>

<% content_for :sidebar do %>

<%= form_for :membership, html: {class: "form-horizontal", role: "form"}, url: "notifications/edit" do |f| %>

<fieldset>
  <legend>Reminder Settings</legend>

  <div class="form-group">
    <div class="col-md-12">
      <div class="checkbox">
        <label><%= f.check_box :daily_reminder %> Daily Schedule Reminder</label>
      </div>
      <div class="checkbox">
        <label><%= f.check_box :weekly_reminder%> Weekly Schedule Reminder</label>
      </div>
      <hr />
        <div class="checkbox">
        <label><%= f.check_box :mine_only %> Send only if I have tickets.</label>
      </div>
    </div>
  </div>

</fieldset>

<div class="row">
  <div class="text-right col-md-12">
    <%= f.hidden_field :form_type, :value => 'reminders' %>
    <%= f.submit 'Update Settings', :class => 'btn btn-default' %>
  </div>
</div>

<% end %>

<% end %>

<% content_for :page_footer do %>
<% end %>

app/views/groups/index.html.erb
<% content_for :page_title do %>Groups<% end %>

<p class="lead">Groups of users exchange tickets among its membership. You can assign tickets to other users, or request their available tickets.</p> 

<hr />

<div class="row">

	<% for group in @groups %>
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="pull-right">
					<% if group.admin?(current_user) %>
					<%= link_to raw('<span class="label label-primary">Administrator</span>'), :action => 'edit', :id => group.id %>
					<% else %>
					<%= link_to raw('<span class="label label-default">Member</span>'), :action => 'edit', :id => group.id %>
					<% end %>
				</div>
				<strong class="group_name"><%= link_to group.group_name, :action => 'show', :id => group.id %></strong>
			</div>
			<div class="panel-body">
				<ul class="list-unstyled text-center">
					<li style="line-height: 120px">
						<%= image_tag group.avatar.url(:thumb) %>
					</li>
					<li>Your <strong><%= group.entity.entity_name %></strong> group.</li>
					<li>
						<%= group.members.count %> members.
					</li>
				</ul>
				<hr />
				<ul class="list-inline text-center">
					<li><%= link_to 'Switch to Group', {:action => 'show', :id => group.id }, :class => 'btn btn-default' %></li>
					<% if !group.admin?(current_user) %>
					<li><%= link_to 'Leave Group', {:action => 'leave', :id => group.id }, :class => 'btn btn-default' %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
	<% end %>
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>Join or Create a Group</strong>
			</div>
			<div class="panel-body">
				<p class="text-center">
					You can create a new group<br />
					to share your season tickets.
				</p>
				<hr />
				<ul class="list-inline text-center">
					<li><%= link_to 'Join a Group', groups_join_path, :class => 'btn btn-primary' %></li>
					<li><%= link_to 'Create a Group', groups_new_path, :class => 'btn btn-primary' %></li>
				</ul>
			</div>
		</div>
	</div>

</div>

<% content_for :page_footer do %>
<% end %>

app/views/groups/invite.html.erb
<% content_for :page_title do %><%= "Invite Member to #{@group.group_name}" %><% end %>

<div class="jumbotron">
  <p>Anyone with <%= link_to 'this link', @invite_link %> can join your ticket group.</p>
  <h5 class="visible-lg"><%= link_to @invite_link, @invite_link %></h5>
  <p class="visible-lg">
    <button class="btn btn-default btn-clipboard" data-clipboard-text="<%= @invite_link %>"><span class="fa fa-clipboard"></span> Copy to Clipboard</button>
  </p>
</div>

<%= form_for @group_invitation, html: {class: "form-horizontal", role: "form"}, url: { :controller => 'groups', :action => 'invite', :id => @group.id } do |f| %>

<div class="row">
  <div class="col-md-12">
    <fieldset>
      <legend>Invite a New Member via Email</legend>
      <div class="form-group">
        <%= f.label :email, :class => 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :email, :class => 'form-control', :placeholder => 'someone@example.com' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :message, :class => 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.text_area :message, :class => 'form-control', :placeholder => 'Write a personal message so they know it\'s you. (optional)' %>
        </div>
      </div>
    </fieldset>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <p class="text-right">
      <%= f.submit 'Send Invitation', :class => 'btn btn-primary' %>
    </p>
  </div>
</div>

<% end %>

<% content_for :page_footer do %>
<% end %>

app/views/groups/join.html.erb
<% content_for :page_title do %>Join a Group<% end %>

<%= form_for :group, html: {class: "form-horizontal", role: "form"}, url: groups_join_path do |f| %>

<fieldset>
  <legend>Join a Group</legend>
  <p class="lead">To join a group, please enter the invitation code provided to you from the group administrator. It may have been included in an email.</p>
  <div class="form-group">
  	<%= f.label :invitation_code, :class => 'col-md-3 control-label' %>
  	<div class="col-md-9">
      <%= f.text_field :invitation_code, autofocus: true, :class => 'form-control', :placeholder => 'ABCDEFG123', :value => @invite_code %>
  	</div>
  </div>
</fieldset>

<div class="row">
	<div class="col-md-12">
		<p class="text-right">
			<%= f.submit 'Join the Group', :class => 'btn btn-primary' %>
		</p>
	</div>
</div>

<% end %>

<% content_for :page_footer do %>
<% end %>

app/views/groups/leave.html.erb
<% content_for :page_title do %><%= "Leave #{@group.group_name}" %><% end %>

<%= form_for @group, html: {class: "form-horizontal", role: "form"}, url: { :controller => 'groups', :action => 'leave', :id => @group.id } do |f| %>

<div class="alert alert-danger alert-block">
	<h3>Are you sure you want to leave "<strong><%= @group.group_name %></strong>?"</h3>
	<ul class="list">
		<li>Your created tickets will be deleted</li>
		<li>Your assigned tickets will show "Unassigned"</li>
		<li>You will have to be invited again to join the group</li>
	</ul>
	<p class="text-right">
		<%= f.hidden_field :id, :value => @group.id %>
		<%= f.submit 'Leave the Group', :class => 'btn btn-danger' %>
	</p>
</div>

<% end %>

<% content_for :page_footer do %>
<% end %>

app/views/groups/new.html.erb
<% content_for :page_title do %>Create a Group<% end %>

<%= form_for @group, url: new_group_path, html: {class: "form-horizontal", role: "form"} do |f| %>

<fieldset>
  <legend>Create a Season Ticket Group</legend>

  <p class="lead">A ticket group exchanges tickets among its membership. You can assign tickets to other users, or request their available tickets.</p> 

  <hr />

  <ol class="user-steps">
    <li>
      <h3>Pick a team</h3>
      <p class="lead">This is how we will organize your tickets.</p>
      <div class="well">
        <%= f.label :entity, 'Your Team', :class => 'sr-only control-label'  %>
        <div>
          <% if @entity %>
          <p class="form-control-static"><%= @entity.display_name %></p>
          <%= f.hidden_field :entity_id, :value => @entity.id %>
          <% else %>
          <%= select_tag 'group[entity_id]', grouped_options_for_select(@entities), { :class => 'form-control', :prompt => '' } %>
          <p class="help-block"><strong>Choose carefully!</strong> You cannot change your team after the group is created.</p>
          <% end %>
        </div>
      </div>
    </li>
    <li>
      <h3>Invite your friends!</h3>
      <p class="lead">You will be able to to send group invitations on the next screen.</p>
    </li>
  </ol>
</fieldset>

<hr />

<div class="row">
  <div class="text-right col-md-12">
    <%= f.submit 'Create Group', :class => 'btn btn-primary' %>
  </div>
</div>

<br />

<% end %>

<% content_for :sidebar do %>
<div class="alert alert-info">
  <h4>I have an invitation code</h4>
  <p>If you received an invitation to join an existing group, <%= link_to 'enter your invitation code', groups_join_path %>.</p>
</div>

<div class="alert alert-info">
  <h4>Can I browse for public groups?</h4>
  <p>SeatShare does not yet have "open" ticket groups. Create a group and invite your friends to get started.</p>
</div>
<% end %>

<% content_for :page_footer do %>
<% end %>

app/views/groups/welcome.html.erb
<% content_for :page_title do %>SeatShare<% end %>
<% content_for :page_description do %>SeatShare<% end %>

<div>

  <p class="lead">
    <strong>Your account is now ready!</strong> Just one more thing before you can begin sharing your tickets.
  </p>

</div>

<div class="row">

  <div class="col-md-6">
    <div class="well">
      <h2>Create a Group</h2>
      <p>Invite your group members to create their accounts and join your group. You can still join a group later.</p>
      <p class="text-right">
        <%= link_to 'Create a Group', groups_new_path, :class => 'btn btn-primary' %>
      </p>
    </div>
  </div>

  <div class="col-md-6">
    <div class="well">
      <h2>Join a Group</h2>
      <p>Simply enter your access code on the next page to join an existing group. You can join more than one group.</p>
      <p class="text-right">
        <%= link_to 'Join a Group', groups_join_path, :class => 'btn btn-primary' %>
      </p>
    </div>
  </div>

</div>

<% content_for :page_footer do %>
<% end %>