config/routes.rb
SeatShare::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => {:registrations => "registrations"}, :path => '/', :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }

  # Default route for app is authenticated, so will redirect
  root 'groups#current'

  devise_scope :user do
    get "register/group/:group_code", to: "registrations#new", as: 'register_with_group_code'
    get "register/invite/:invite_code", to: "registrations#new", as: 'register_with_invite_code'
    get "register/:entity_slug/:entity_id", to: "registrations#new", as: 'register_with_entity_id'
  end

  get 'groups/' => 'groups#index'
  get 'groups/new' => 'groups#new', as: 'new_group'
  post 'groups/new' => 'groups#create'
  get 'groups/join' => 'groups#join', as: 'join_group'
  post 'groups/join' => 'groups#do_join'
  get 'groups/join/:invite_code' => 'groups#join'
  get 'groups/:id' => 'groups#show', as: 'group'
  get 'groups/:id/edit' => 'groups#edit', as: 'edit_group'
  patch 'groups/:id/edit' => 'groups#update'
  post 'groups/:id/notifications/edit' => 'groups#update_notifications'
  get 'groups/:id/leave' => 'groups#leave', as: 'leave_group'
  patch 'groups/:id/leave' => 'groups#do_leave'
  get 'groups/:id/invite' => 'groups#invite', as: 'invite_group'
  post 'groups/:id/invite' => 'groups#do_invite'
  post 'groups/:id/reset_invite' => 'groups#do_reset_invite'
  get 'groups/:id/deactivate' => 'groups#deactivate', as: 'deactivate_group'
  patch 'groups/:id/deactivate' => 'groups#do_deactivate'
  get 'groups/:id/message' => 'groups#message', as: 'message_group'
  post 'groups/:id/message' => 'groups#do_message'
  get 'groups/:id/events_feed' => 'groups#events_feed'
  post 'groups/:id/schedule_notify' => 'groups#do_request_notify'

  get 'groups/:group_id/event-:id' => 'events#show'

  get 'groups/:group_id/event-:event_id/ticket-:id' => 'tickets#edit'
  post 'groups/:group_id/event-:event_id/ticket-:id' => 'tickets#update'
  get 'groups/:group_id/event-:event_id/ticket-:id/unassign' => 'tickets#unassign'
  get 'groups/:group_id/event-:event_id/ticket-:id/delete' => 'tickets#delete'
  get 'groups/:group_id/event-:event_id/ticket-:ticket_id/ticket-file/:id/delete' => 'tickets#delete_ticket_file', as: 'delete_ticket_file'
  get 'groups/:group_id/add-tickets' => 'tickets#new'
  post 'groups/:group_id/add-tickets' => 'tickets#create'
  get 'groups/:group_id/event-:event_id/add-ticket' => 'tickets#new'
  post 'groups/:group_id/event-:event_id/add-ticket' => 'tickets#create'
  get 'groups/:group_id/event-:event_id/ticket-:id/request' => 'tickets#request_ticket'
  patch 'groups/:group_id/event-:event_id/ticket-:id/request' => 'tickets#do_request_ticket'

  get 'tickets' => 'tickets#index'
  get 'tickets/:filter' => 'tickets#index'
  post 'tickets' => 'tickets#bulk_update'

  get 'calendar' => 'calendar#index'
  get 'calendar/full/:token' => 'calendar#full'
  get 'groups/:group_id/calendar/:token' => 'calendar#group'

  resource :user, path: 'profile', only: [:show, :edit, :update] do
    resources :aliases, controller: :user_aliases
  end
  resources :users, path: 'profiles', only: [:show]

  match '/404' => 'errors#error404', via: [:get, :post, :patch, :delete]

  namespace :admin_api, defaults: {format: 'json'} do
    namespace :v1 do
      root 'admin_api#index'
      get ':action' => 'admin_api#:action'
    end
  end

end

app/models/user.rb
##
# User model
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tickets, dependent: :destroy, foreign_key: :owner_id
  has_many :user_aliases, dependent: :destroy
  has_many :memberships, dependent: :delete_all
  has_many :groups, through: :memberships, dependent: :destroy,
                    foreign_key: :creator_id

  before_save :clean_calendar_token

  validates :first_name, :last_name, :email, presence: true

  scope :by_name, (-> { order('LOWER(last_name) ASC, LOWER(first_name) ASC') })
  scope :active, (-> { where(status: true) })

  attr_accessor :entity_id
  attr_accessor :newsletter_signup
  attr_accessor :invite_code

  ##
  # Check if active for authentication
  def active_for_authentication?
    super && status?
  end

  ##
  # New user object
  # - attributes: attributes for object
  def initialize(attributes = {})
    attr_with_defaults = {
      status: true
    }.merge(attributes)
    super(attr_with_defaults)
  end

  ##
  # Display name for user
  def display_name
    "#{first_name} #{last_name}"
  end

  ##
  # Default gravatar based on email
  # - dimensions: string of avatar size in `NxN` format
  def gravatar(dimensions = '30x30')
    require 'digest/md5'
    email_address = email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    "https://www.gravatar.com/avatar/#{hash}?s=#{dimensions}&d=mm"
  end

  ##
  # Format mobile phone number in `+11235551234` format
  def mobile_e164
    GlobalPhone.normalize(mobile)
  end

  ##
  # Bio as Markdown
  def bio_md
    renderer = Redcarpet::Render::HTML.new(filter_html: true)
    markdown = Redcarpet::Markdown.new(renderer, autolink: true)
    markdown.render(bio || '')
  end

  ##
  # User Can View?
  # - user: instance of user to see if they have a common group
  def user_can_view?(user)
    return false if user.nil?
    return true if user.id == id
    shared_users = []
    groups.collect do |group|
      group.members.collect do |u|
        shared_users << u.id
      end
    end
    return true if shared_users.include? user.id
    false
  end

  ##
  # Destroy
  def destroy
    Ticket.where(user_id: id).find_each do |ticket|
      ticket.user_id = 0
      ticket.save!
    end
    super
  end

  private

  ##
  # Generate a unique calendar token
  def generate_calendar_token
    SecureRandom.urlsafe_base64(nil, false)
  end

  ##
  # Run calendar token generator if not set
  def clean_calendar_token
    self.calendar_token = generate_calendar_token if calendar_token.blank?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
##
# Users :: OminiAuth Callbacks Controller
module Users
  ##
  # Users :: OminiAuth Callbacks Controller
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.persisted?
        sign_in_and_redirect @user
        set_flash_message(
          :notice, :success, kind: 'Facebook'
        ) if is_navigational_format?
      else
        session['devise.facebook_data'] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
##
# Users
module Users
  ##
  # Registrations controller
  class RegistrationsController < Devise::RegistrationsController
    skip_before_filter :require_no_authentication
    before_filter :redirect_to_join_if_signed_in, if: :user_signed_in?

    ##
    # New registration form
    def new
      @user = User.new
      if params[:invite_code]
        @invite = GroupInvitation.find_by_invitation_code(params[:invite_code])
      else
        @invite = nil
      end
      if params[:entity_id]
        @entity = Entity.find_by_id(params[:entity_id])
      else
        @entity = nil
      end
      if params[:group_code]
        @group = Group.find_by_invitation_code(params[:group_code])
      else
        @group = nil
      end
      super
    end

    ##
    # Process new registration
    def create
      build_resource(sign_up_params)

      if resource.save

        # Send welcome email
        WelcomeEmail.welcome(resource).deliver_now

        # Newsletter signup
        if params[:newsletter_signup] == '1' && !ENV['MAILCHIMP_LIST_ID'].nil?
          subscribe_newsletter
        end

        send_conversion
        notify_slack(resource)

        yield resource if block_given?
        if resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_flashing_format?
          sign_up(resource_name, resource)
          if params[:user][:invite_code]
            register_with_invitation_code(params[:user][:invite_code], resource)
          elsif params[:user][:entity_id]
            entity_id = params[:user][:entity_id]
            respond_with(
              resource,
              location: groups_new_path + '?entity_id=' + entity_id
            )
          else
            respond_with resource, location: groups_new_path
          end
        else
          set_flash_message(
            :notice, :"signed_up_but_#{resource.inactive_message}"
          ) if is_flashing_format?
          expire_data_after_sign_in!
          respond_with(
            resource,
            location: after_inactive_sign_up_path_for(resource)
          ) && return
        end
      else
        flash[:alert] = 'There were errors with your registration.'
        clean_up_passwords resource
        respond_with resource
      end
    end

    ##
    # Process email and password updates
    def update
      super
    end

    ##
    # Overwrite update_resource to let users to update their user
    # without giving their password
    def update_resource(resource, params)
      if current_user.provider == 'facebook'
        params.delete('current_password')
        resource.update_without_password(params)
      else
        resource.update_with_password(params)
      end
    end

    private

    ##
    # Redirect to Join if Signed In
    def redirect_to_join_if_signed_in
      if params[:group_code] || params[:invite_code]
        redirect_to(
          controller: 'groups',
          action: 'join',
          invite_code: "#{params[:group_code]}#{params[:invite_code]}"
        ) && return
      end
      require_no_authentication unless %w(edit update).include? params[:action]
    end

    ##
    # Register with Invitation Code
    def register_with_invitation_code(invitation_code = nil, resource = nil)
      group = Group.join_with_invitation_code(invitation_code, resource)
      if group
        respond_with(
          resource,
          location: group_path(id: group.id)
        ) && return
      end
      respond_with(
        resource,
        location: root_path
      ) && return
    end

    ##
    # Subscribe Newsletter
    def subscribe_newsletter
      require 'mailchimp'
      mailchimp = Mailchimp::API.new(ENV['MAILCHIMP_API_KEY'])
      merge_vars = {
        'FNAME' => sign_up_params[:first_name],
        'LNAME' => sign_up_params[:last_name]
      }
      mailchimp.lists.subscribe(
        ENV['MAILCHIMP_LIST_ID'],
        { 'email' => sign_up_params[:email] },
        merge_vars,
        'html',
        false,
        true,
        false,
        false
      )
    rescue Mailchimp::Error => e
      # Sign up failed
      logger.info e.message
    end

    ##
    # Send Conversion
    def send_conversion
      # Measure in Google Analytics
      GoogleAnalyticsApi.new.event('user', 'signup', params[:ga_client_id])

      # Mark as Converted for Google AdWords
      flash[:conversion] = true
    end

    ##
    # Notify Slack
    def notify_slack(user = nil)
      return if user.nil? || ENV['SLACK_WEBHOOK_URL'].nil? ||
                Rails.env != 'production'
      notifier = Slack::Notifier.new ENV['SLACK_WEBHOOK_URL']
      notifier.ping "New user: #{user.display_name} <#{user.email}>",
                    icon_emoji: ':bust_in_silhouette:',
                    username: 'Signup Notifications'
    rescue StandardError => e
      logger.info e.message
    end
  end
end

app/controllers/users_controller.rb
##
# Users controller
class UsersController < ApplicationController
  before_action :authenticate_user!
  layout 'two-column'

  ##
  # Show a user profile
  def show
    @user = User.find_by(id: params[:id]) || current_user
    not_found unless current_user.user_can_view? @user
  end

  ##
  # Edit the current user's profile
  def edit
    @user = current_user
    @user_aliases = current_user.user_aliases.by_name
  end

  ##
  # Process the edits for current user's profile
  def update
    user = current_user
    user.update_attributes!(user_params)

    flash.keep
    flash[:notice] = 'Profile updated!'
    redirect_to(action: :show, id: @current_user.id) && return
  end

  private

  ##
  # Strong parameters for user profile
  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :timezone, :bio, :location, :mobile, :sms_notify
    )
  end
end

app/views/users/_add_mobile_alerts.html.erb
<% if current_user.mobile.blank? %>
<div class="panel panel-default">
  <div class="panel-body">
    <div class="sidebar-icon"><%= link_to raw('<span class="fa fa-mobile"></span>'), user_path %></div>
    <h3>Never miss an alert from SeatShare</h3>
    <p>Add your mobile phone number to receive a text message when someone requests or assigns you a ticket.</p>
    <p><%= link_to 'Add Mobile Number', user_path, class: 'btn btn-primary' %></p>
  </div>
</div>
<% end %>

app/views/users/_add_tickets.html.erb
<% if @group.tickets.count.zero? && @group.events.future.count > 0 %>
<div class="panel panel-default">
  <div class="panel-body">
    <div class="sidebar-icon"><%= link_to raw('<span class="fa fa-ticket"></span>'), { :controller => 'tickets', :action => 'new', :group_id => @group.id } %></div>
    <h3>Add Your Tickets</h3>
    <p>Have tickets for your group? Add them to SeatShare.</p>
    <p><%= link_to 'Add Tickets', { :controller => 'tickets', :action => 'new', :group_id => @group.id }, class: 'btn btn-primary' %></p>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<% content_for :page_title do %>Edit Profile<% end %>

<%= form_for @user, :url => user_path, html: {class: "form-horizontal", role: "form"} do |f| %>

  <fieldset>
    <legend>Your Details</legend>

    <div class="form-group">
      <%= f.label :first_name, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :first_name, :class => 'form-control', :placeholder => 'John' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :last_name, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :last_name, :class => 'form-control', :placeholder => 'Doe' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :timezone, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.time_zone_select :timezone, nil, { include_blank: true }, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-3 col-md-9">
        <span><%= link_to "Change your email or password", edit_user_registration_path %></span>
      </div>
    </div>

    <hr />

    <div class="form-group">
      <%= f.label :bio, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_area :bio, :class => 'form-control', :placeholder => 'Who is your favorite team?' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :location, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :location, :class => 'form-control', :placeholder => 'Any Town, USA' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :mobile, :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :mobile, :class => 'form-control', :placeholder => '(555) 555-1234' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :sms_notify, 'SMS Notifications', :class => 'col-md-3 control-label' %>
      <div class="col-md-9">
        <label><%= f.check_box :sms_notify %> Receive notifications when tickets are assigned or requested.</label>
        <p class="help-block">
        Standard messaging rates apply. Messages will originate from <strong><%= number_to_phone ENV['TWILIO_OUTBOUND_NUMBER'].gsub('+1','') %></strong>.
        </p>
      </div>
    </div>
  </fieldset>

  <div class="row">
    <div class="col-md-12">
        <p class="text-right">
          <%= f.submit 'Update Profile', :class => 'btn btn-primary' %>
        </p>
    </div>
  </div>

<% end %>

<% content_for :sidebar do %>

<fieldset>
  <legend>Aliases</legend>
  <p class="text-muted">"Aliases" allow you to flag tickets that are assigned to you, but under a different name, such as your spouse or sibling. You can create as many aliases as you need.</p>

  <% if @user_aliases.count > 0 %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th class="action">&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% for user_alias in @user_aliases %>
      <tr>
        <td><%= link_to user_alias.display_name, edit_user_alias_path(user_alias) %></td>
        <td><%= link_to raw('<span class="fa fa-trash"></span>'), user_alias_path(user_alias), :method => 'delete', :class => 'btn btn-sm btn-danger confirm' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>

  <p class="text-right">
    <%= link_to raw('<span class="fa fa-plus"></span> Add Alias'), { :controller => 'user_aliases', :action => 'new' }, :class => 'btn btn-default' %>
  </p>

</fieldset>

<% end %>

<% content_for :page_footer do %>
<% end %>

app/views/users/show.html.erb
<% content_for :page_title do %><%= "#{@user.display_name}" %><% end %>

<div class="row">
  <div class="col-md-3">
    <p>
      <%= image_tag @user.gravatar('250x250'), :class => 'img-thumbnail img-responsive', :alt => @user.display_name, :title => @user.display_name %>
    </p>
  </div>
  <div class="col-md-9">
    <% if current_user === @user %>
    <p class="pull-right">
      <%= link_to raw('<span class="fa fa-pencil"></span> Edit Profile'), { :action => 'edit' }, :class => 'btn btn-default' %>
    </p>
    <% end %>
    <h2><%= @user.display_name %></h2>
    <p><small class="text-muted"> <%= !@user.location.blank? ? @user.location : '<em>No Location Set</em>'.html_safe %> <span class="fa fa-map-marker"></span></small></p>

    <div class="lead"><%= raw(@user.bio_md) %></div>

    <br />
    <ul class="list-group">
      <li class="list-group-item profile-email"><span class="fa fa-envelope"></span> <%= mail_to @user.email, @user.email %></li>
      <li class="list-group-item profile-joined"><span class="fa fa-user"></span> Joined <%= @user.created_at.strftime('%B %-d, %Y') %></li>
      <li class="list-group-item profile-mobile"><span class="fa fa-phone"></span> <%= !@user.mobile.blank? ? number_to_phone(@user.mobile) : 'Not Provided' %></li>
    </ul>
  </div>
</div>

<% content_for :page_footer do %>
<% end %>