config/routes.rb
SeatShare::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => {:registrations => "registrations"}, :path => '/', :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }

  # Default route for app is authenticated, so will redirect
  root 'groups#current'

  devise_scope :user do
    get "register/group/:group_code", to: "registrations#new", as: 'register_with_group_code'
    get "register/invite/:invite_code", to: "registrations#new", as: 'register_with_invite_code'
    get "register/:entity_slug/:entity_id", to: "registrations#new", as: 'register_with_entity_id'
  end

  get 'groups/' => 'groups#index'
  get 'groups/new' => 'groups#new', as: 'new_group'
  post 'groups/new' => 'groups#create'
  get 'groups/join' => 'groups#join', as: 'join_group'
  post 'groups/join' => 'groups#do_join'
  get 'groups/join/:invite_code' => 'groups#join'
  get 'groups/:id' => 'groups#show', as: 'group'
  get 'groups/:id/edit' => 'groups#edit', as: 'edit_group'
  patch 'groups/:id/edit' => 'groups#update'
  post 'groups/:id/notifications/edit' => 'groups#update_notifications'
  get 'groups/:id/leave' => 'groups#leave', as: 'leave_group'
  patch 'groups/:id/leave' => 'groups#do_leave'
  get 'groups/:id/invite' => 'groups#invite', as: 'invite_group'
  post 'groups/:id/invite' => 'groups#do_invite'
  post 'groups/:id/reset_invite' => 'groups#do_reset_invite'
  get 'groups/:id/deactivate' => 'groups#deactivate', as: 'deactivate_group'
  patch 'groups/:id/deactivate' => 'groups#do_deactivate'
  get 'groups/:id/message' => 'groups#message', as: 'message_group'
  post 'groups/:id/message' => 'groups#do_message'
  get 'groups/:id/events_feed' => 'groups#events_feed'
  post 'groups/:id/schedule_notify' => 'groups#do_request_notify'

  get 'groups/:group_id/event-:id' => 'events#show'

  get 'groups/:group_id/event-:event_id/ticket-:id' => 'tickets#edit'
  post 'groups/:group_id/event-:event_id/ticket-:id' => 'tickets#update'
  get 'groups/:group_id/event-:event_id/ticket-:id/unassign' => 'tickets#unassign'
  get 'groups/:group_id/event-:event_id/ticket-:id/delete' => 'tickets#delete'
  get 'groups/:group_id/event-:event_id/ticket-:ticket_id/ticket-file/:id/delete' => 'tickets#delete_ticket_file', as: 'delete_ticket_file'
  get 'groups/:group_id/add-tickets' => 'tickets#new'
  post 'groups/:group_id/add-tickets' => 'tickets#create'
  get 'groups/:group_id/event-:event_id/add-ticket' => 'tickets#new'
  post 'groups/:group_id/event-:event_id/add-ticket' => 'tickets#create'
  get 'groups/:group_id/event-:event_id/ticket-:id/request' => 'tickets#request_ticket'
  patch 'groups/:group_id/event-:event_id/ticket-:id/request' => 'tickets#do_request_ticket'

  get 'tickets' => 'tickets#index'
  get 'tickets/:filter' => 'tickets#index'
  post 'tickets' => 'tickets#bulk_update'

  get 'calendar' => 'calendar#index'
  get 'calendar/full/:token' => 'calendar#full'
  get 'groups/:group_id/calendar/:token' => 'calendar#group'

  resource :user, path: 'profile', only: [:show, :edit, :update] do
    resources :aliases, controller: :user_aliases
  end
  resources :users, path: 'profiles', only: [:show]

  match '/404' => 'errors#error404', via: [:get, :post, :patch, :delete]

  namespace :admin_api, defaults: {format: 'json'} do
    namespace :v1 do
      root 'admin_api#index'
      get ':action' => 'admin_api#:action'
    end
  end

end

app/views/layouts/_adwords.html.erb
<!-- Google Code for New Account Conversion Page -->
<% if ENV['ADWORDS_CONVERSION_ID'] && ENV['ADWORDS_CONVERSION_LABEL'] %>
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = <%= ENV['ADWORDS_CONVERSION_ID'].to_i %>;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "<%= ENV['ADWORDS_CONVERSION_LABEL'] %>";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/<%= ENV['ADWORDS_CONVERSION_ID'].to_i %>/?label=<%= ENV['ADWORDS_CONVERSION_LABEL'] %>&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<% end %>

app/views/layouts/_analytics.html.erb
<% if !ENV['GOOGLE_ANALYTICS_ID'].nil? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV['GOOGLE_ANALYTICS_ID'] %>', 'app.myseatshare.com');
  ga('send', 'pageview');

  <% if user_signed_in? %>
  ga('set', '&uid', '<%= current_user.id %>');
  <% end %>

</script>
<% end %>

app/views/layouts/_data_credit.html.erb
<% if @entity.seatgeek? %>
<p class="data-credit text-muted text-right">Data powered by <%= link_to image_tag('seatgeek.svg', :class => '', :alt => "SeatGeek", :title => "SeatGeek Logo"), 'https://seatgeek.com/', :target => '_blank' %>.</p>
<% end %>

app/views/layouts/_flash.html.erb
<% if !flash.empty? %>
  <% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible" role="alert">
  	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  	<%= flash[:notice] %>
  </div>
  <% end %>
  <% if flash[:alert] %>
  <div class="alert alert-info alert-dismissible" role="alert">
  	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  	<%= flash[:alert] %>
  </div>
  <% end %>
  <% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible" role="alert">
  	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  	<%= flash[:error] %>
  </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <div class="row">
        <div class="col-md-12">
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p>
                <em>Provided by <%= link_to 'SeatShare', :root %></em>
            </p>
        </div>
    </div>
</footer>

app/views/layouts/_ios.html.erb
<%= favicon_link_tag 'touch-icon-iphone.png', rel: 'apple-touch-icon', type: 'image/png' %>
<%= favicon_link_tag 'touch-icon-ipad.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '76x76' %>
<%= favicon_link_tag 'touch-icon-iphone-retina.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '120x120' %>
<%= favicon_link_tag 'touch-icon-ipad-retina.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '152x152' %>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="apple-mobile-web-app-title" content="SeatShare">
<meta name="apple-mobile-web-app-capable" content="yes" />

app/views/layouts/_meta_tags.html.erb
<meta name="description" content="<%= yield :page_description || 'SeatShare is the easiest way to manage your group season tickets.' %>" />

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="logo">
        <%= link_to "SeatShare", :root, :class => 'navbar-brand' %>
      </div>
    </div>
    <div class="navbar-collapse collapse">
      <% if user_signed_in? %>
      <% if !@group_selector.blank? && !@group.nil? %>
      <form class="navbar-form navbar-left" role="form" id="group_switcher" method="get">
        <div class="form-group">
          <%= select_tag 'group_selector', options_for_select(@group_selector, @group.id), { :class => 'form-control' } %>
        </div>
      </form>
      <% end %>
      <ul class="nav navbar-nav">
        <li class=""><%= link_to "Groups", groups_path %></li>
        <li class=""><%= link_to "Tickets", tickets_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to current_user.display_name, edit_user_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, :method => :destroy %></li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to 'Create Account', new_user_registration_path, title: 'Create Account' %></li>
        <li><%= link_to 'Login', new_user_session_path, title: 'Login' %></li>
      </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8">

<title><%= yield :page_title || 'SeatShare' %></title>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>

<meta charset="utf-8">

<%= favicon_link_tag 'favicon.png', rel: 'shortcut icon', type: 'image/png' %>

<%= render 'layouts/meta_tags' %>

<%= render 'layouts/ios' %>

<%= render 'layouts/analytics' %>

<%= yield :html_head %>

</head>
<body class="default">

<%= render 'layouts/navbar' %>

<%= yield :page_header %>

<div class="container">

<%= render 'layouts/flash' %>

<%= yield %>

<%= render 'layouts/footer' %>

</div>

<%= yield :page_footer %>

<%= render 'layouts/adwords' if flash[:conversion] == true %>

</body>
</html>

app/views/layouts/email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width">
    <title><%= headers[:subject] || 'SeatShare' %></title>
    <%= stylesheet_link_tag 'mailers/email' %>
  </head>

  <body>
    <table class="body" data-made-with-foundation="">
      <tr>
        <td class="float-center" align="center" valign="top">
          <center data-parsed="">
            <table bgcolor="#4963AE" align="center" class="wrapper header float-center">
              <tr>
                <td class="wrapper-inner">
                  <table align="center" class="container">
                    <tbody>
                      <tr>
                        <td>
                          <table class="row collapse">
                            <tbody>
                              <tr>
                                <th class="small-12 large-12 columns first last" valign="middle">
                                  <table>
                                    <tr>
                                      <th>
                                        <%= link_to image_tag("http://email-assets.seatsha.re/email-header-600x100.png", :alt => 'SeatShare Logo', :style => 'max-width:600px;', :only_path => false), root_url, { only_path: false } %>
                                      </th>
                                    </tr>
                                  </table>
                                </th>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
            </table>
            <table align="center" class="container float-center">
              <tbody>
                <tr>
                  <td>
                    <table class="spacer">
                      <tbody>
                        <tr>
                          <td height="16px" style="font-size:16px;line-height:16px;">&#xA0;</td>
                        </tr>
                      </tbody>
                    </table>
                    <table class="row">
                      <tbody>
                        <tr>
                          <th class="small-12 large-12 columns first last">
                            <table>
                              <tr>
                                <th>
                                  <% if !(yield :header).blank? %>
                                  <%= yield :header %>
                                  <% end %>
                                </th>
                                <th>
                                  <%= yield %>
                                </th>
                                <th class="expander"></th>
                              </tr>
                            </table>
                          </th>
                        </tr>
                      </tbody>
                    </table>
                    <table class="wrapper secondary" align="center">
                      <tr>
                        <td class="wrapper-inner">
                          <table class="spacer">
                            <tbody>
                              <tr>
                                <td height="16px" style="font-size:16px;line-height:16px;">&#xA0;</td>
                              </tr>
                            </tbody>
                          </table>
                          <table class="row">
                            <tbody>
                              <tr>
                                <th class="small-12 large-12 columns first last">
                                  <table>
                                    <tr>
                                      <th class="text-center">
                                        <% if !(yield :footer).blank? %>
                                        <%= yield :footer %>
                                        <% else %>
                                        Sent through <%= link_to 'SeatShare', root_url, { only_path: false } %>.
                                        <% end %>
                                      </th>
                                    </tr>
                                  </table>
                                </th>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </center>
        </td>
      </tr>
    </table>
    <% if !@view_action.blank? %>
    <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "EmailMessage",
      "potentialAction": {
        "@type": "ViewAction",
        "target": "<%= @view_action[:url] %>",
        "name": "<%= @view_action[:action] %>"
      },
      "description": "<%= @view_action[:description] %>",
      "publisher": {
        "@type": "Organization",
        "name": "SeatShare",
        "url": "https://app.myseatshare.com"
      }
    }
    </script>
    <% end %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8">

<title><%= yield :page_title || 'SeatShare' %></title>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>

<meta charset="utf-8">

<%= favicon_link_tag 'favicon.png', rel: 'shortcut icon', type: 'image/png' %>

<%= render 'layouts/meta_tags' %>

<%= render 'layouts/ios' %>

<%= render 'layouts/analytics' %>

<%= yield :html_head %>

</head>

<body class="login">

<%= yield :page_header %>

<div class="container">

  <div class="logo">
    <h1><%= link_to 'SeatShare', :root %></h1>
  </div>

  <%= yield %>

</div>

<%= yield :page_footer %>

<%= render 'layouts/adwords' if flash[:conversion] == true %>

</body>
</html>

app/views/layouts/single-column.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8">

<title><%= yield :page_title || 'SeatShare' %></title>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>

<meta charset="utf-8">

<%= favicon_link_tag 'favicon.png', rel: 'shortcut icon', type: 'image/png' %>

<%= render 'layouts/meta_tags' %>

<%= render 'layouts/ios' %>

<%= render 'layouts/analytics' %>

<%= yield :html_head %>

</head>
<body class="single-column">

<%= render 'layouts/navbar' %>

<%= yield :page_header %>

<div class="container">

<%= render 'layouts/flash' %>

<%= yield %>

<%= render 'layouts/footer' %>

</div>

<%= yield :page_footer %>

<%= render 'layouts/adwords' if flash[:conversion] == true %>

</body>
</html>

app/views/layouts/two-column.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8">

<title><%= yield :page_title || 'SeatShare' %></title>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>

<meta charset="utf-8">

<%= favicon_link_tag 'favicon.png', rel: 'shortcut icon', type: 'image/png' %>

<%= render 'layouts/meta_tags' %>

<%= render 'layouts/ios' %>

<%= render 'layouts/analytics' %>

<%= yield :html_head %>

</head>
<body class="two-column">

<%= render 'layouts/navbar' %>

<%= yield :page_header %>

<div class="container">

  <div class="row">
    <section class="col-md-8">

    <%= render 'layouts/flash' %>

    <%= yield %>

    </section>

    <nav class="col-md-4">
      <%= yield :sidebar %>
    </nav>
  </div>

<%= render 'layouts/footer' %>

</div>

<%= yield :page_footer %>

<%= render 'layouts/adwords' if flash[:conversion] == true %>

</body>
</html>